title: Pretrained Language Models are Symbolic Mathematical Solvers Too!
description: [Kimia Noorbakhsh](kimianoorbakhsh@gmail.com), Modar Sulaiman, Mahdi Sharifi, Kallol Roy, and Pooyan Jamshidi 
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman